version: '3.7'
services:

  ### NGINX #########################################
  nginx:
    build:
      context: ./docker/nginx
    container_name: "laravel_vue_nginx"
    volumes:
      - ./:/var/www/webserver
      - ./.dock-data/logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"

  ### WorkSpace #########################################
  workspace:
      build: ./docker/workspace
      container_name: "laravel_vue_workspace"
      volumes:
        - ./:/var/www/webserver
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  ### MySQL #########################################
  mysql:
    build:
      context: ./docker/mysql
    container_name: "laravel_vue_mysql"
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    volumes:
      - ./.dock-data/mysql:/var/lib/mysql
      - ./.dock-data/logs/mysql:/var/log/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  ### Radis #########################################
  redis:
      image: redis:6.0
      volumes:
          - ./.dock-data/redis:/data
      ports:
          - "6379:6379"
